server:
  port: 8443
  ssl:
    key-alias: server
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    client-auth: need
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12

logging:
  level:
    root: debug
